agent_options:
  config:
    decorators:
      load:
      - SELECT uuid AS host_uuid FROM system_info;
      - SELECT hostname AS hostname FROM system_info;
    options:
      disable_distributed: false
      distributed_interval: 10
      distributed_plugin: tls
      distributed_tls_max_attempts: 3
      logger_tls_endpoint: /api/osquery/log
      logger_tls_period: 10
      pack_delimiter: /
  overrides:
labels:
org_settings:
  certificate_authorities:
    custom_scep_proxy:
    digicert:
    - api_token: 01c83396e8e86350a5e1a8fa13_1cec34383eb86e776b4942d49623cf49cbc5c8c03286730b5500d1c56d1e4262
      certificate_common_name: $FLEET_VAR_HOST_HARDWARE_SERIAL@fleetdm.com
      certificate_seat_id: $FLEET_VAR_HOST_HARDWARE_SERIAL@fleetdm.com
      certificate_user_principal_names:
      - $FLEET_VAR_HOST_HARDWARE_SERIAL@fleetdm.com
      name: WIFI_CERTIFICATE
      profile_id: e71a1f4f-dced-4992-a0d5-a93f3b724ea3
      url: https://demo.one.digicert.com
    hydrant:
    - client_id: 6d500faba9295bfbe6efdeabf348f5d7
      client_secret: 6d500faba9295bfbe6efdeabf348f5d7
      name: WIFI_CERTIFICATE_ABC
      url: https://acm-stage.hydrantid.com/.well-known/est/552b5178-4e14-49a9-9408-e4cab4355db7
    - client_id: 6d500faba9295bfbe6efdeabf348f5d7
      client_secret: 6d500faba9295bfbe6efdeabf348f5d7
      name: WIFI_CERTIFICATE
      url: https://acm-stage.hydrantid.com/.well-known/est/552b5178-4e14-49a9-9408-e4cab4355db7
    ndes_scep_proxy:
  features:
    enable_host_users: true
    enable_software_inventory: true
  fleet_desktop:
    transparency_url: https://fleetdm.com/transparency
  host_expiry_settings:
    host_expiry_enabled: false
    host_expiry_window: 0
  integrations:
    conditional_access_enabled: false
    google_calendar:
    jira:
    zendesk:
  mdm:
    apple_business_manager:
    apple_server_url:
    end_user_authentication:
      entity_id: PezHub_DEP
      idp_name: Okta
      issuer_uri:
      metadata:
      metadata_url: https://dev-16134854.okta.com/app/exkhtcahqpIxIVYps5d7/sso/saml/metadata
    end_user_license_agreement:
    volume_purchasing_program:
  org_info:
    contact_url: https://fleetdm.com/company/contact
    org_logo_url:
    org_logo_url_light_background:
    org_name: PezHub
  secrets:
  - secret: JJnWAvoquuAbRmzqDmbVQYcSXOCXBbYs
  server_settings:
    ai_features_disabled: false
    deferred_save_host: false
    enable_analytics: true
    live_query_disabled: false
    query_report_cap: 0
    query_reports_disabled: false
    scripts_disabled: false
    server_url: https://pezhub.ngrok.app
  sso_settings:
    enable_jit_provisioning: false
    enable_sso: false
    enable_sso_idp_login: false
    entity_id:
    idp_image_url:
    idp_name:
    metadata:
    metadata_url:
    sso_server_url:
  webhook_settings:
    activities_webhook:
      destination_url:
      enable_activities_webhook: false
    failing_policies_webhook:
      destination_url:
      enable_failing_policies_webhook: false
      host_batch_size: 0
      policy_ids:
    host_status_webhook:
      days_count: 0
      destination_url:
      enable_host_status_webhook: false
      host_percentage: 0
    interval: 24h0m0s
    vulnerabilities_webhook:
      destination_url:
      enable_vulnerabilities_webhook: false
      host_batch_size: 0
  yara_rules:
policies:
queries:
- automations_enabled: false
  description: Collects operating system information from all devices enrolled in
    Fleet
  discard_data: false
  interval: 300
  logging: snapshot
  min_osquery_version:
  name: Collect operating system information
  observer_can_run: true
  platform: darwin,linux,windows
  query: SELECT * FROM os_version;
